

spring:
  application:
    name: ai-app-generator

server:
  port: 8100
  servlet:
    context-path: /api

# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.morfism.aiappgenerator.controller
# knife4j????? ???? http://localhost:8100/api/doc.html#/home
knife4j:
  enable: true
  setting:
    language: zh_cn