

spring:
  application:
    name: ai-app-generator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_generator
    username: root
    password: 283401
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  session:
    store-type: redis
    timeout: 2592000

server:
  port: 8100
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.morfism.aiappgenerator.controller
# knife4j????? ???? http://localhost:8100/api/doc.html#/home
knife4j:
  enable: true
  setting:
    language: zh_cn